---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: vcs-trigger-fe
spec:
  params:
    - name: source-repo
      value: $(body.repository.url)
    - name: commit
      value: $(body.head_commit.id)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vcs-trigger-fe
spec:
  params:
    - name: source-repo
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: express-app-one-pipeline-run-
      spec:
        params:
          - name: source-repo
            value: https://github.com/cloud-native-garage-method-cohort/apac-3-grp-2-app-frontend
          - name: image-repo
            value: quay.io/arief_hidayat/apac-3-grp-2-feedback-frontend-service
          - name: app-name
            value: feedback-frontend
        serviceAccountName: build-bot
        pipelineRef:
          name: nodejs-pipeline
        workspaces:
          - name: pipeline-shared-data
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: vcs-trigger-fe
spec:
  serviceAccountName: vcs-trigger
  triggers:
    - bindings:
        - ref: vcs-trigger-fe
      template:
        name: vcs-trigger-fe
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: vcs-trigger-fe
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: el-vcs-trigger-fe
    weight: 100