apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: apac-3-cngm-project-php
  app.kubernetes.io/instance: apac-3-cngm-project-php-instance
  app.kubernetes.io/name: apac-3-cngm-project-php
